apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t0ioz33rb-python
  janus-idp.io/tekton: t0ioz33rb-python
  backstage.io/kubernetes-id: t0ioz33rb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t0ioz33rb-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
